### ISSUE TITLE
Reflecting UI changes to the route

### ISSUE THREAD

**Issue by ImanMh** [kriasoft/universal-router#104]
Sometimes this would be grate to have UI state in route. for example in a list that is filtered with some check boxes. When the user clicks on a checkbox I like the route to change so that the user is able to share that route or bookmark it. I don't want to use ```#``` since Google will ignore it. currently if I do something like this:

```javascript
import history from './history';
history.replace('/itemts/filter=discount,new');
``` 
It will change the position of my scroll. How can I implement such a thing?

**Comment by frenzzy** [comment]
The trick is to disable native [History API Scroll Restoration](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration) behavor and control scroll manually.
One of implementation examples you can find here: [React-Starter-Kit/src/client.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/client.js)

**Comment by ImanMh** [comment]
Yea but sounds like it can never find the ```pos``` because current key is not present in the ```scrollPositionsHistory[location.key]``` 

![keys](https://user-images.githubusercontent.com/4482199/29428546-d83616b2-83a2-11e7-8e67-1cd9b91fc765.png)
![current key](https://user-images.githubusercontent.com/4482199/29428547-d837dcf4-83a2-11e7-96ae-35c8eae5220e.png)

So pos object is never created. What am I doing wrong?

**Comment by frenzzy** [comment]
If location key does not exist that means the page is opened first time and we usually scroll to top in this case (as for non SPA apps).

**Comment by ImanMh** [comment]
For me changing line 163 of ```client.js``` to this solved scroll jump on ```history.push``` or ```history.replace```

```javascript
      () => onRenderComplete(route, { ...location, key: Object.keys(scrollPositionsHistory).pop() }),
```

@frenzzy I took a look at ```client.js``` and I don't know what I have to change to preserve scroll position during route change. Can you help me out?

**Comment by frenzzy** [comment]
You need to decide in which case you don't need to scroll. For example you may skip scrolling if path wasn't changed or if `history.replace` were used.
```js
if (!(previousLocation.pathname === location.pathname && action === 'REPLACE')) {
  window.scrollTo(scrollX, scrollY);
}
```

**Comment by ImanMh** [comment]
That should do the job but my question is since ```scrollPositionsHistory``` is an object and I don't have previous location key, How can I access last position history in ```scrollPositionsHistory``` ? I'm thinking that If scrollPositionsHistory was an array it could be really easy just to pick the last element of it. Am I missing something?

**Comment by frenzzy** [comment]
```js
let previousLocation = history.location;
function onLocationChange(location) {
  // here you have both location and previousLocation
  previousLocation = location;
}
```

**Comment by ImanMh** [comment]
Thanks a lot you are so helpful.
