### ISSUE TITLE
Named routes?

### ISSUE THREAD

**Issue by nathanmarks** [kriasoft/universal-router#11]
Any plans to add named routes? Hardcoding hrefs feels very permanent. Named routes allow you to completely separate URL structure logic from your views.

I understand that you're trying to keep this lightweight -- however I feel having named routes and a transition function that takes the parameters as args helps keep all URL related logic in the router.

Otherwise, URL changes mean switching out hrefs in the views.

Thoughts?

**Comment by koistya** [comment]
@nathanmarks starting from `v1.0.0` the router works with routes declared as plain JavaScript objects where you can add any arbitrary fields other than `path` and `action`. For example, you can add `name` field like so:

```js
const routes = [
  { name: 'home', path: '/', action() { ... } },
  { name: 'account', path: '/account', action() { ... } },
];
```

The use it in your URL builder utility, for example `createHref(routes, 'account')` or `createHref = createHref.bind(undefined, routes); createHref('account');`.

Does this cover your use case?

**Comment by nathanmarks** [comment]
@koistya Should do the trick! Thanks.
