### ISSUE TITLE
docs issue?

### ISSUE THREAD

**Issue by bfreis** [kriasoft/universal-router#12]
Hi Konstantin,

Could the docs for react-routing be outdated? The README file shows examples of `router.use(...)` and `router.route(...)`, but those don't seem to work or exist in the source code.

Thanks!
Bruno
##

**Comment by koistya** [comment]
Yep, the docs are outdated. Here is a usage sample:

https://github.com/kriasoft/react-starter-kit/blob/master/src/routes.js

**Comment by puradox** [comment]
+1

**Comment by richb-hanover** [comment]
Yes. react-starter-kit has switched to use @koistya's universal-router. There's a great overview of it at http://slides.com/koistya/universal-router and you can check out the repo at https://github.com/kriasoft/universal-router

**Comment by frenzzy** [comment]
[Docs](https://github.com/kriasoft/universal-router/tree/master/docs) had been updated to reflect the latest API changes.
