### ISSUE TITLE
Multiple route paths with same params

### ISSUE THREAD

**Issue by juusaw** [kriasoft/universal-router#121]
It seems that using multiple paths with same route parameters within a route overwrites the parameters for some routes. This can be reproduced by defining a route like this:

```
const route = {
  path: ['/one/:parameter', '/two/:parameter'],
  action: ({ params }) => { console.log(params) }
}
```

When navigating to the former route, params seems to contain the key `parameter` but the value is `undefined`. The latter route works as expected, yielding a value for the parameter.

I tested the case with version 3.2.0 and 4.0.0.

**Comment by frenzzy** [comment]
For review: #122
