### ISSUE TITLE
TypeError: Expected "number" to be a string

### ISSUE THREAD

**Issue by luongthanhlam** [kriasoft/universal-router#139]
When I call url('user', { id: 11, slugs: 'abc' }), it throw an error
```
TypeError: Expected "number" to be a string
    at Object.toPath (/.../node_modules/path-to-regexp/index.js:188:13)
    at /.../node_modules/universal-router/src/generateUrls.js:78:39
```
Here are my routes.js:
```
 { name: 'user', path: ['/:id(\\d+)-:slugs/page-:number(\\d+)', '/:id(\\d+)-:slugs'] }
```

**Comment by frenzzy** [comment]
`generateUrls` uses the first path from array of paths which is contains required `:number(\\d+)` parameter in your example. You must provide the param or swap the paths.

**Comment by luongthanhlam** [comment]
When I swap paths, only the first part work
```
url('user', { id: 11, slugs: 'abc', number: 22 }) //=>/user/11-abc
```

**Comment by frenzzy** [comment]
Which the path `url()` should generate?

**Comment by luongthanhlam** [comment]
Well, I fixed it by adding the missing param but I think generateUrls should uses all paths from array of paths, not only the first.

**Comment by frenzzy** [comment]
Could you provide an example what URL should be generated in your case then?

**Comment by luongthanhlam** [comment]
Oh yes, here is an example in my case:
```
url('user', { id: 11, slugs: 'abc' }) //=> /11-abc
url('user', { id: 11, slugs: 'abc', number: 200 }) //=> /11-abc/200
```

**Comment by frenzzy** [comment]
You can make the latest parameter optional:
```js
const route = {
  name: 'user',
  path: '/:id(\\d+)-:slugs/:number?' // <== question mark
}

url('user', { id: 11, slugs: 'abc' }) // => /11-abc
url('user', { id: 11, slugs: 'abc', number: 200 }) // => /11-abc/200
```
Playground: http://jsfiddle.net/frenzzy/h3Lfz42q/
Read more: [path-to-regexp parameters](https://github.com/pillarjs/path-to-regexp#parameters)

**Comment by luongthanhlam** [comment]
Thank you, it works perfectly
