### ISSUE TITLE
Full url - with origin, not just the path

### ISSUE THREAD

**Issue by AhmedSayed77** [kriasoft/universal-router#142]
Is their a way to get the full url? I define the route like this '/home' but Sometimes I want to generate the route line this 'www.myawesomeapp.com/home'

**Comment by frenzzy** [comment]
How about this?
```js
import UniversalRouter from 'universal-router';
import generateUrls from 'universal-router/generateUrls';

const router = new UniversalRouter({ name: 'home', path: '/home' });

const path = generateUrls(router);
const url = (...args) => `https://www.example.com${path(...args)}`;

url('home'); // => https://www.example.com/home
```
Playground: http://jsfiddle.net/frenzzy/jwcbme5x/

**Comment by AhmedSayed77** [comment]
already thought of that, but having development server in local machine, staging server and a production server makes it's hard to hard code the origin

**Comment by frenzzy** [comment]
Then you can use environment variables in your server-side code instead of hard coded values or use current host aka `req.get('host')`.

On client side you can use the origin which was returned from backend side or `window.location.origin`

**Comment by AhmedSayed77** [comment]
Thinking about it, as universal router is "universal" it should not contain logic related to the browser. thanks for your time, I'm gona close the issue, and try to figure out the solution

**Comment by AhmedSayed77** [comment]
Great idea. Also I can solve the problem from the history package I'm using, that sounds more appropriate.
where's the "close issue" button? :smile: . Please close the issue.
