### ISSUE TITLE
Provide option for strict routing via path-to-regexp

### ISSUE THREAD

**Issue by nickspiel** [kriasoft/universal-router#155]
**I'm submitting a ...**

* [ ] bug report
* [x] feature request

I am looking to serve different pages for paths with and without trailing slashes.

**Current behaviour:**
```
// Requesting /some-path/
/:var(some-path) // Should not match but does
/:var(some-path)/ // Never gets hit as first route matches
```

**Desired behaviour:**
```
// Requesting /some-path/
/:var(some-path) // Does not match
/:var(some-path)/ // Matches
```

It looks like universal-router uses the non-strict version of [path-to-regexp](https://github.com/pillarjs/path-to-regexp) and there is no option to request [strict routing](https://github.com/pillarjs/path-to-regexp#usage). It would be great to have the option to enable strict mode through the universal-router [config option](https://github.com/kriasoft/universal-router/blob/master/src/UniversalRouter.js#L26).

**Comment by frenzzy** [comment]
You can just use the right order of rotues to reach the same result:
```js
const routes = [
  { path: '/some-path/', action: () => 'A' },
  { path: '/some-path',  action: () => 'B' },
]

const router = new UniversalRouter(routes)

router.resolve('/some-path/') // => A
router.resolve('/some-path')  // => B
```
Demo: https://codepen.io/frenzzy/pen/MXjrOB?editors=0010

**Comment by nickspiel** [comment]
Okay - it was my mistake my A route needed to be `/:channel(for-sale|for-lease)(/.*)`.

Thanks for the assistance and for an awesome project!

Closing.
