### ISSUE TITLE
update path-to-router dependency to latest

### ISSUE THREAD

**Issue by mattlohkamp** [kriasoft/universal-router#186]
**I'm submitting a ...**
* [x] feature request
This project explicitly mentions that `path-to-router` is its sole dependency, but the truth is it's using a version that's nearly 6 months out of date, which means instead of doing this:
```javascript
const router = new UniversalRouter([
 {
  route:'/compare,:id1{,:id2}?{,:id3}?',
 }
]);
```
we need to work around the lack of optional custom prefix/suffix groups using child routes, which is an unnecessary obstacle to human readability and maintainability.

Is there anything in particular preventing this project from using the latest version of `path-to-router`?

**Comment by frenzzy** [comment]
Hi! I have WIP PR for that: #183 need to just finish with todos.
