### ISSUE TITLE
Incorrect TypeScript RouteParams Interface

### ISSUE THREAD

**Issue by plemarquand** [kriasoft/universal-router#189]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

The interface for RouteParams is:

```js
export interface RouteParams {
  [paramName: string]: string | string[]
}
```
(https://github.com/kriasoft/universal-router/blob/master/src/UniversalRouter.ts#L39)

However its possible for route parameters to be optional:

```js
const routes = [
  { name: 'user', path: '/user/:username?' }
]
```

Leading me to think the RouteParams interface should look like:

```js
export interface RouteParams {
  [paramName: string]: string | string[] | undefined;
}
```

**Comment by frenzzy** [comment]
If parameter is present its value always a string and can't be undefined ([CodePen](https://codepen.io/frenzzy/pen/abvraqW?editors=0010)):
```js
import UniversalRouter from 'universal-router';

const router = new UniversalRouter({
  path: '/user/:username?',
  action: ({ params }) => JSON.stringify(params)
})

router.resolve('/user').then(console.log)      // => {}
router.resolve('/user/').then(console.log)     // => {}
router.resolve('/user/demo').then(console.log) // => {"username":"demo"}
```
i.e. `{ "username": undefined }` is not possible.

**Comment by plemarquand** [comment]
You're right, I should be guarding property existence on maps with `hasOwnProperty` instead. Closing.
