### ISSUE TITLE
URL redirect && `dispatch` to return promise

### ISSUE THREAD

**Issue by zhming0** [kriasoft/universal-router#23]
I am trying to think of a way to do redirection. 
Here are some examples, of which one requires dispatch to return promise.

```
// Redirect / to /home
{on("/", async() => {
     const {state, component} = await this.dispatch("/home");
     return component;
})}
```

Or provide a new api  `redirect` (same level as `on`)?

```
redirct("/", "/home");
```

Apparently second one is better. Maybe adding this will be good? 
##

**Comment by Palgie** [comment]
+1

I'd prefer API if there is no loss of scope when used alongside conditionals.

**Comment by koistya** [comment]
What do you think about this API? Where a route with redirect looks like this:

```js
const router = new Router();

router.addRoute({
  path: '/',
  action: ({ redirect }) => redirect('/home') // alternatively redirect('/home', permanent)
});
```

which would be the same as running:

```js
// The list of routes may come from an external file, e.g. `import routes from './routes';`
const routes = [
  {
    path: '/',
    action: ({ redirect }) => redirect('/home')
  }
];

const router = new Router(routes);
```

a shorthand version should also work:

```js
const router = new Router(on => {
  on('/', ({ redirect }) => redirect('/home'));
});

See [named-routes](https://github.com/kriasoft/react-routing/compare/named-routes) branch.
```

**Comment by Palgie** [comment]
@koistya Yep - That would work for my use case!

**Comment by koistya** [comment]
@zhming0 yep, adding `router.redirect(fromPath, toPath)` method for configuring static redirects would be nice. PR is welcome!

**Comment by v3yr0n** [comment]
Was this done? If yes, how can i use it? :)

**Comment by JeongTaekLim** [comment]
Thanks @koistya for pretty simple example. I've tried to follow as above. 

```Javascript
import {resolve} from 'universal-router';
import Router from 'universal-router';

....

request.post({
  url: 'http://localhost:8000/account/create/',
  form
}, (err, res, body) => {
  const router = new Router().route('/', ({redirect}) => redirect('/login'));
  }
});
```

but I got an error about webpack.

```
TypeError: __WEBPACK_IMPORTED_MODULE_4_universal_router___default.a is not a constructor
```

I'm using react-starter-kit-react-redux.
What I want to do is just change the user registration page into login page.

**Comment by frenzzy** [comment]
@JeongTaekLim answer regarding your error: https://github.com/kriasoft/universal-router/issues/127#issuecomment-332552740

Docs about [redirects](https://github.com/kriasoft/universal-router/blob/master/docs/redirects.md) added. Closing.
