### ISSUE TITLE
Post queries?

### ISSUE THREAD

**Issue by gorbs** [kriasoft/universal-router#25]
Using the react-starterkit setup and have added a new route /authenticate. When I post to the route, I get a response "Cannot POST /authenticate". However, it will happily route to it via a GET.

for example:
`on('/authenticate', async () => <div>hello</div>);`
will error with a POST, but return the element with a GET. Does the router support POST operations or am I doing something very wrong?

**Comment by langpavel** [comment]
I think you do not instrument `express` to handle HTTP `POST` method in [`server.js`](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js).
Please read more about express.

**Comment by koistya** [comment]
This router is only supposed to be used with GET HTTP requests for rendering React apps on the server and on the client. To add `/authenticate` endpoint on the server, you can use Express functionality, for example, in `server.js`:

```js
app.post('/authenticate', (req, res) => {
  // todo: validate user, issue an authentication token
});
```
