### ISSUE TITLE
Rename match() to resolve()

### ISSUE THREAD

**Issue by koistya** [kriasoft/universal-router#26]
What do you think about renaming `match()` method to `resolve()`? This method doesn't only find the route matching the given URL path, but also executes its action method and returns result to the caller.

**Comment by langpavel** [comment]
Hmm, will you deprecate `match` method with some kind of decorator? :-)
I'm happy with `match`...

**Comment by frenzzy** [comment]
- [v1.2.1](https://github.com/kriasoft/universal-router/blob/master/CHANGELOG.md#v122---2016-05-31): `match()` renamed to `resolve()`
- [v2.0.0](https://github.com/kriasoft/universal-router/blob/master/CHANGELOG.md#v200---2016-10-20): `match()` removed, use `resolve()` instead
