### ISSUE TITLE
how do you redirect to a route outside of the system?

### ISSUE THREAD

**Issue by jordan112** [kriasoft/universal-router#29]
For example, how would I redirect to an external site, such as http://google.com

The reason I ask, my application site is a different site than my marketing public site, so when a user signs out, i actually want to redirect them to a url not in the application

**Comment by jordan112** [comment]
and just a FYI, not talking about just a simple link that user clicks, this would be a redirect done programmatically.  I'm using the React Starter Kit

**Comment by langpavel** [comment]
You don't want redirection on HTTP level, right? Just user click and (do you want to track him?) will be redirected. It's plain old `<a href="..."></a>`.

Yeah, you wish track user?

**Comment by jordan112** [comment]
so not a plain <a>.  Want to accomplish this programmatically.  For example, a user clicks the sign out link....that goes to the server server, logs out, kills tokens, what not, then i redirect the user to a different site.  I believe react-router, something to this affect, just to illustrate an example:

    router.redirectTo('http://www.google.com')

**Comment by langpavel** [comment]
Hmm, I'm not sure.. User click just one time, I am right? .... Who cares... just.. what do you want from universal-router? I'm still don't catching you point.. You can redirect outside by many ways. Do you asking or trying?

**Comment by jordan112** [comment]
Actually, the more i think about it, this isn't a universal router issue, rather just a straight up node.js redirect

    res.redirect('http://app.example.io');

http://stackoverflow.com/questions/28352871/in-express-how-do-i-redirect-a-user-to-an-external-url

Closing this issue.  Thanks for the feedback.

**Comment by Download** [comment]
Just for future viewers: The client-side redirect equivalent would just be:

```js
location = 'http://app.example.io';
```

which would send the user away to the other site.
