### ISSUE TITLE
Update UMD builds to include 3rd party libraries

### ISSUE THREAD

**Issue by koistya** [kriasoft/universal-router#32]
UMD builds must include `path-to-regexp` and `babel-runtime` libraries:

https://npmcdn.com/universal-router@1.2.1/universal-router.js
https://npmcdn.com/universal-router@1.2.1/universal-router.min.js

In order to fix that, edit UMD bundle configuration in `/tools/build.js`.

Also, update `README.md` file to include info how to use UMD builds from CDN.

**Comment by frenzzy** [comment]
This is done!
- https://npmcdn.com/universal-router@2.0.0/universal-router.js
- https://npmcdn.com/universal-router@2.0.0/universal-router.min.js

Demo: https://jsfiddle.net/kLau68jx/
