### ISSUE TITLE
Question: How to get a parameter in the app.js file

### ISSUE THREAD

**Issue by v3yr0n** [kriasoft/universal-router#37]
Hey!
@koistya if possible can you tell me how can I get a parameter, in this case the language locale, in the app.js file (the entrance file)?

Thanks!

**Comment by v3yr0n** [comment]
I ended up doing this, in the app.js file: 
`var lang = document.location.toString().match("\/([a-z]{2})\/")[1];`
I'm sure this is not the best approach, but.. :)

**Comment by langpavel** [comment]
You should pass your language from router action to your rendering code.

**Comment by frenzzy** [comment]
Looks like the router has an issue with `path` and `params` in routes with parents: https://jsfiddle.net/frenzzy/os15zm7f/

**Comment by frenzzy** [comment]
```js
import { resolve } from 'universal-router';

let lang = 'en-US'; // by default
const routes = {
  path: '/:locale',
  action(context) {
    lang = context.params.locale;
  },
  children: [
    { path: '/one', action(context) {
      return `<h1>One (${context.params.locale})</h1>`
    } },
    { path: '/two', action(context) {
      return `<h1>Two (${context.params.locale})</h1>`
    } },
  ],
};

UniversalRouter.resolve(routes, { path: '/zh-CN/one' }).then(result => {
  document.body.innerHTML = result; // renders: <h1>One (zh-CN)</h1>
  console.log(lang); // => zh-CN
});
```

Demo: https://jsfiddle.net/v4yabwdu/
