### ISSUE TITLE
Why should someone use this over react-router?

### ISSUE THREAD

**Issue by bearcott** [kriasoft/universal-router#44]
I'm wondering if anyone with experience using this knows any of the pros/cons? 
##

**Comment by langpavel** [comment]
**Pros:** Simple
**Cons:** Too simple :smiling_imp: 
**TODO:** Documentation

**Comment by apexskier** [comment]
I don't have a ton of experience with either, but one thing I like about this is that it's not dependent on react itself.

**Comment by gustavohenke** [comment]
A huge pro: the combination of code splitting and hot reloading just works™

It's incredibly hard to make react-router v4 + react-hot-loader v3 + stateless components work right.

**Comment by frenzzy** [comment]
The answer in the [docs](https://github.com/kriasoft/universal-router/tree/master/docs#why-use-universal-router):
* It has [simple code](https://github.com/kriasoft/universal-router/blob/master/src/Router.js) with only single [path-to-regexp](https://github.com/pillarjs/path-to-regexp) dependency
* It can be used with any JavaScript framework such as React, Vue.js etc
* It uses the same middleware approach used in Express and Koa, making it easy to learn
* Routes are plain javascript objects with which you can interact as you like
* Support both imperative and declarative routing style
