### ISSUE TITLE
A version of Universal Router that does not depend on generators

### ISSUE THREAD

**Issue by Download** [kriasoft/universal-router#52]
Hi, I just wanted to let you guys know that I love Universal Router. I think it's a brilliant piece of code!

I ended up forking it though, because I didn't want to include babel-runtime and babel-regenerator-runtime in my web bundle. I released the fork as [uroute](https://npmjs.com/package/uroute). Maybe it can be of use to others that can't / don't want to depend on generator functions.
##

**Comment by frenzzy** [comment]
Since [v3.0.0](https://github.com/kriasoft/universal-router/releases/tag/v3.0.0) universal router does not depends on generators anymore. Thanks for the idea.
