### ISSUE TITLE
context.path gets overwritten by route.path while resolving

### ISSUE THREAD

**Issue by jazblueful** [kriasoft/universal-router#69]
resolve.js line 31:

`const newContext = Object.assign({}, context, value);`

**Comment by jazblueful** [comment]
in the root route I want to do something like this:

```
export default {

  path: '/',

  children: [
    require('./protected1').default,
    require('./protected2').default,
    require('./login').default,
  ],

  async action({ path, query, next }) {
    const route = await next();

    if (path !== '/login' && !isAuthenticated()) {
      const queries = Object.keys(query).map(key => `${key}=${query[key]}`).join('&');
      const location = `${path}?${queries}`;
      route.redirect = `/login?next=${encodeURIComponent(location)}`;
      return route;
    }
    ...
```

And I'm resolving it with:

```
    const route = await UniversalRouter.resolve(routes, {
      path: req.path
    });
```

When navigating to http://mywebsite/login I was expecting path to be '/login' in the root route action, but it's always '/'. For now I'm passing additional _path property to the context and using that instead.

**Comment by frenzzy** [comment]
Since [v3.0.0](https://github.com/kriasoft/universal-router/releases/tag/v3.0.0) you can use `context.url` instead of `_path`. More info about context see in [docs](https://github.com/kriasoft/universal-router/blob/master/docs/api.md#context).
