### ISSUE TITLE
ie8 throw error

### ISSUE THREAD

**Issue by shawon1220** [kriasoft/universal-router#7]
hi,when i use it ie8,thorw one error:

Unhandled promise rejection TypeError: Object does not support the "next" property or method.

async function next() {
      if (({ value, done } = handlers.next()) && !done) {
        const [match, handler] = value;
        state.params = match.params;
        return handler.length > 1 ?
          await handler(state, next) : await handler(state);
      }
    }

**Comment by cwtuan** [comment]
Not work in ie8. How can I fix it?

**Comment by lockelee1015** [comment]
have you fix this bug?
I meet this problem too

**Comment by kongliangyu** [comment]
met same issue

**Comment by Bogdaan** [comment]
@cwtuan
@lockelee1015 
@kongliangyu

This is not "universal-router" issue.
See https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html

How to fix this?
Ans.: downgrade react version.

**Comment by kongliangyu** [comment]
@Bogdaan 
I have already switched to react v0.14. And if I comment out universal-router codes, the app works, if I kept, app breaks...

Could it be a babel polyfill issue or it doesn't support ES3?

I am still looking into this...

**Comment by kongliangyu** [comment]
It's actually an issue from babel runtime polyfill, see: https://github.com/babel/babel/pull/3445

**Comment by frenzzy** [comment]
Old ticket, please reopen if needed.
