### ISSUE TITLE
Query String / Hash Support

### ISSUE THREAD

**Issue by bencompton** [kriasoft/universal-router#77]
Does universal-router plan to support query strings and hashes? From my tests, it appears that these are not currently supported.

For example: 

```
myapp/test?foo=1&bar=5#hash
```

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41090889-query-string-hash-support?utm_campaign=plugin&utm_content=tracker%2F18115217&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F18115217&utm_medium=issues&utm_source=github).

**Comment by koistya** [comment]
Parsing hashes would work only on the client-side (in the browser). Are you using Universal Router in an isomorphic (universal) app or regular SPA?

**Comment by bencompton** [comment]
The short answer is SPA.

I'm actually evaluating it to potentially propose to the author of a [Vue mobile web UI framework](https://github.com/nolimits4web/Framework7-vue). It currently has its own router implementation designed primarily for SPAs, but with a router implementation that worked on the server, it could potentially support server rendering as well. The router implementation supports query strings and hashes, so I was curious about support for these features in universal-router.

**Comment by koistya** [comment]
@bencompton in the current version of the router, there is just a single `UniversalRouter.resolve(routes, context)` method. The second parameter can be customized to pass a query/hash strings as objects, for example:

```js
import Router from 'universal-router';
import qs from 'query-string';
import routes from './routes';

Router.resolve(routes, {
  path: window.location.pathname,
  query: qs.parse(window.location.search),
  hash: qs.parse(window.location.hash),
}).then(render);
```

All this info is passed down to route handler functions, e.g.:

```js
// some-route.js
export default {
  path: '/some-route',
  action({ query, hash }) {
    console.log(query, hash);
    return ...;
  }
}
```

Do you think this will work for your use case, or you have a better idea how to support hashes?

**Comment by bencompton** [comment]
@koistya thanks for the quick response! The current router accepts a string like `/user/45/posts/28/?sort=first#opened` and parses it. universal-router would be wrapped with the API of the current router implementation anyways, so it could certainly pre-parse the strings to separate the path from "other stuff" before passing it all onto universal-router for resolution.

So, universal-router should be perfectly usable as-is for this use case. In an ideal world, though, universal-router might support more generic syntax like this:

```javascript
// some-route.js
export default {
  path: '/user/:userId/posts/:postId/?sort=:sortBy#:hash',
  action({ userId, postId, sortBy, hash }) {
    ...
    return ...;
  }
}
```

``

**Comment by frenzzy** [comment]
```js
import Router from 'universal-router';
import queryString from 'query-string';
import routes from './routes';

// location = '/user/45/posts/28/?sort=first#opened'
Router.resolve(routes, {
  path: location.pathname,
  query: queryString.parse(location.search),
  hash: location.hash,
}).then(render);

const route = {
  path: '/user/:userId/posts/:postId',
  action({ path, params: { userId, postId }, query: { sort }, hash }) {
    console.log(path);   // => '/user/45/posts/28/?sort=first#opened'
    console.log(userId); // => '45'
    console.log(postId); // => '28'
    console.log(sort);   // => 'first'
    console.log(hash);   // => '#opened'
    return /*...*/;
  }
}
```
Playground: https://jsfiddle.net/frenzzy/1gk5mh1d/

**Comment by bencompton** [comment]
@frenzzy, using the URL object looks like a really simple way to pre-parse a URL string and querystring is a nice, small library. That's perfect--thanks!
