### ISSUE TITLE
Make params available to child routes

### ISSUE THREAD

**Issue by gmuresan** [kriasoft/universal-router#79]
I have a route that has an :id parameter and also contains a bunch of children. The children of this route need access to the :id parameter but right now the only way to get it is to parse context.baseUrl.

There should be a way to access the params from the parent route in each of the children.

**Comment by frenzzy** [comment]
This feature was implemented in #57 and available since [v2.0.0](https://github.com/kriasoft/universal-router/blob/master/CHANGELOG.md#v200---2016-10-20).
Playground: https://jsfiddle.net/frenzzy/gfLrh6s8/
Please let us know if you are having trouble with it.

**Comment by gmuresan** [comment]
Thank you. My parent route had a parameter that had the same name as the child parameter, so it was being overwritten by the child.
