### ISSUE TITLE
i18n paths

### ISSUE THREAD

**Issue by alopes** [kriasoft/universal-router#84]
So I've been banging my head on this one.

Using react-intl, how can I go from 
```
export default {

  path: '/myurl',
```
to
```
export default {

  path: formatMessage({ id: route.myurl }),
```

Thanks! #

**Comment by frenzzy** [comment]
Can you describe a more realistic use case? What kind of page?

For example for static routes with unicode characters need to use encoded path (because HTTP does not allow characters outside the ASCII range):
```js
const route = {
  path: '/caf%C3%A9', // encodeURI('/café') or `/${encodeURIComponent('café')}`
  action(context) {
    console.log(context.path) // => '/caf%C3%A9'
  },
};

const location = new URL('http://example.com/café'); // like window.location
UniversalRouter.resolve(route, location.pathname);
```
But in your case probably need to use dynamic path params:
```js
const route = {
  path: '/:name',
  action(context, params) {
    if (params.name === 'café') { // or check for any localized paths
      return 'page';
    }
    return null; // page not found
  }
};
```

**Comment by alopes** [comment]
@frenzzy, thanks for the feedback. With your help, I was able to get it running!
