### ISSUE TITLE
API fetch calls

### ISSUE THREAD

**Issue by AntonyKwok** [kriasoft/universal-router#85]
Hi,

When using Universal Router with React Starter Kit, any API requests using either fetch or Axios (for example in `routes/home/index.js`) will call the API endpoint twice.

Any idea why?

**Update March 25:**
The double call only happens when server-side rendering is called. Accessing the route client-side triggers a single API request.

**Comment by frenzzy** [comment]
This issue does not relate to the router, please take a look at:
- https://github.com/kriasoft/react-starter-kit/issues/813 - How to avoid the duplicate request for SSR
- https://github.com/kriasoft/react-starter-kit/issues/983 - Home fetch run twice
