### ISSUE TITLE
path case-sensitive?

### ISSUE THREAD

**Issue by HelloYie** [kriasoft/universal-router#90]
How can i set the url case-sensitive? 
Now 
```
/somEPAth/
/somePath/
/somepath/
```
got the same result.

**Comment by frenzzy** [comment]
This option is not available right now, but it should be easy to pass `sensitive` option from router to [path-to-regexp](https://github.com/pillarjs/path-to-regexp). Can you explain why you need it and how do you plan to use it with an example?

**Comment by HelloYie** [comment]
@frenzzy  Thanks. I think it is not must be.
