### ISSUE TITLE
Full support of query params

### ISSUE THREAD

**Issue by apsavin** [kriasoft/universal-router#92]
Hi guys!
Thanks for the awesome work!

I want to suggest a feature: full support of query params. Query params should be first-class citizens of a router. For example, when I generate an url `generateUrl(routeName, params)`, I want a router to generate a full url, including query params. All params that are not a part of a route itself should go to the query part.

For example:

0. Route name: 'user'
1. Route path: `/user/:username`
2. `generateUrl('user', {username: 'John', busy: 1})` should generate `/user/John?busy=1`

Of course, there should be a possibility to provide a function to generate query strings.

I know, you want to keep the router tiny and simple. So I'll not wonder if you decline this feature request. But:

1. Such feature will bring simplicity for router users.
2. There's no proper way to implement such feature outside of router (Well, there's a way with handling query params as separate object: `generateUrl(routeName, params, queryParams)`, but I don't think that user of `generateUrl` function should think what params are belong to route and what should go to query string.)

**Comment by apsavin** [comment]
I can come with a PR.

**Comment by koistya** [comment]
@apsavin that would be nice!
